---
title: "annotation_time"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r load_libraries}
library(tidyverse)
library(knitr)
```

```{r load_data}
listened_time <- read_csv("listened_time_more_columns.csv")
#csv from webster's code output, column names fixed by hand and separated into subj/month columns in excel
```


```{r first_dive}
averages <- listened_time %>%
  group_by(month) %>%
  summarise(mean(total_listen_hr), sd(total_listen_hr), min(total_listen_hr), max(total_listen_hr), n())

kable(averages)
```

22_09 is only file missing (check)


max for 8, 9, 10 month, all > 2 standard deviations away from mean

```{r histogram}
listened_time %>%
  ggplot(aes(total_listen_hr)) + 
  geom_histogram(binwidth = 1) + 
  coord_cartesian(xlim = c(0,16)) +
  facet_wrap( ~ month, scales = "free_x")

```



which files to check for too much time

```{r overage}

eight_mo_over <- listened_time %>%
  filter(month == 8) %>%
  filter(total_listen_hr > 4.0)

```


